workflows:
  ria-digidoc-ios:
    name: RIA DigiDoc iOS
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      xcode: 15.3
    scripts:
      - name: Create sample files
        script: |
          cd ./MoppApp
          touch GoogleService-Info.plist
          cat <<EOF > GoogleService-Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>Sample key</key>
              <string>Sample value</string>
          </dict>
          </plist>
          EOF

          cd ./MoppApp
          touch config.json
          touch publicKey.pub
          touch signature.rsa
          touch defaultConfiguration.json
      - name: Get RIA DigiDoc version
        script: |
          cd ./MoppApp
          echo "APP_VERSION=$('/usr/bin/xcodebuild' -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =')" >> $CM_ENV
      - name: Build
        script: |
          cd ./MoppApp
          xcodebuild build archive -archivePath "./build/RIA_DigiDoc_$APP_VERSION.$PROJECT_BUILD_NUMBER.xcarchive" -configuration Release -scheme "MoppApp" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO GOOGLE_CONF_REQUIRED=NO
    artifacts:
      - ./MoppApp/build/RIA_DigiDoc_$APP_VERSION.$PROJECT_BUILD_NUMBER.xcarchive
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true
